apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: r12d7cxot-python-gitops
  description: This is GitOps manifest for r12d7cxot-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: r12d7cxot-python
    janus-idp.io/tekton: r12d7cxot-python
    backstage.io/kubernetes-id: r12d7cxot-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:r12d7cxot-python
